service: final-daily-inspiration-node
frameworkVersion: '3'
useDotenv: true

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action: SNS:Publish
          Resource: !Ref QuotesMessages
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    SENDGRID_API_KEY: "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"
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:934827452929:quotes-messages-dev
    SNS_EMAIL_ENDPOINT: ${env:SNS_EMAIL_ENDPOINT}

package:
  patterns:
    - '!front-end/**'

functions:
  quotes:
    handler: handlers/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: GET
          cors: true
  subscribe:
    handler: handlers/subscribeUser.subscribeUser
    events:
      - http:
          path: subscribe
          method: post
          cors: true
  staticMailer:
    handler: handlers/staticMailer.staticMailer
    events:
      - http:
          path: static-mailer
          method: post
          cors: true
  sendEmail:
    handler: handlers/sendEmail.sendEmail
    events:
      - http:
          path: send-email
          method: post
          cors: true
      - schedule: cron(0 13 * * ? *)
  getSubscribers:
    handler: handlers/getSubscribers.getSubscribers
    events:
      - http:
          path: subscribers
          method: get
          cors: true

resources:
  Resources:
    #SNS
    QuotesMessages:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: quotes-messages-${self:provider.stage}
    QuotesMessagesSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref QuotesMessages
        Protocol: email
        Endpoint:  ${self:environment.SNS_EMAIL_ENDPOINT}
        DeliveryPolicy:
          healthyRetryPolicy:
            numRetries: 20
            minDelayTarget: 30
            maxDelayTarget: 600
            backoffFunction: exponential



    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
